import { createServer } from 'node:http';
import { serveLabs, type FixtureOrder } from './labs.ts';
export function startDemo(port = Number(process.env.DEMO_PORT || 4400), fixed = process.env.DEMO_FIXED === '1') {
  const orders = new Map<string, FixtureOrder>();
  const server = createServer(async (req, res) => {
    if (await serveLabs(req, res, fixed, orders)) return;
    if (req.url === '/favicon.ico') { res.writeHead(204); return res.end(); }
    if (req.url === '/api/confirm') {
      res.writeHead(fixed ? 200 : 500, { 'Content-Type': 'application/json' });
      return res.end(JSON.stringify(fixed ? { status: 'confirmed', orderId: 'fixture-001' } : { error: 'Confirmation service unavailable', token: 'seeded-secret-do-not-store', email: 'fixture@example.com', cardNumber: '4242424242424242' }));
    }
    res.writeHead(200, { 'Content-Type': 'text/html' });
    res.end(`<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Acme · Demo Storefront</title><style>body{margin:0;background:#f5f3ed;color:#242c28;font:16px system-ui}nav{display:flex;justify-content:space-between;padding:25px 7%;border-bottom:1px solid #d8dcd5}nav b{font-size:22px;letter-spacing:-1px}main{max-width:980px;margin:65px auto;padding:0 30px}small{letter-spacing:3px;color:#748472}h1{font-size:55px;letter-spacing:-3px;max-width:600px;margin:18px 0}p{color:#6c766e;line-height:1.7}article{margin-top:35px;display:flex;gap:40px;padding:32px;background:white;border:1px solid #e0e4dc;border-radius:18px}.product{width:240px;min-height:200px;background:#e7eddd;border-radius:12px;display:grid;place-items:center;font-size:90px}button{background:#254c3c;color:white;padding:15px 24px;border:0;border-radius:7px;cursor:pointer;font:inherit}#error{color:#ae423a;padding:18px;background:#fff0ed;border-radius:8px}footer{margin:40px 0;color:#849080;font-size:13px}</style></head><body><nav><b>acme / goods</b><span>Collection &nbsp; / &nbsp; Your bag (1)</span></nav><main id="app"><small>MADE FOR YOUR EVERYDAY</small><h1>The everyday collection</h1><p>A few good things. Thoughtfully made, built to stay.</p><article><div class="product" aria-label="Canvas tote illustration">◡</div><div><small>THE ESSENTIALS</small><h2>Everyday canvas tote</h2><p>Natural cotton · Forest green<br>One size · Quantity 1</p><h3>$32.00</h3><button id="checkout">Continue to checkout</button></div></article><footer>Local fixture store. No payments are processed.</footer></main><script>document.getElementById('checkout').onclick=()=>{history.pushState({},'', '/checkout');document.getElementById('app').innerHTML='<small>ONE LAST THING</small><h1>Your next everyday essential.</h1><article><div class="product">◡</div><div><h2>Order summary</h2><p>Everyday canvas tote × 1</p><h3>Total: $32.00</h3><button id="confirm">Confirm order</button><div id="result" aria-live="polite"></div></div></article><footer>Fixture checkout · no real charges</footer>';document.getElementById('confirm').onclick=async()=>{const r=await fetch('/api/confirm',{method:'POST'});const data=await r.json();if(!r.ok){console.error('Checkout confirmation failed: HTTP '+r.status);document.getElementById('result').innerHTML='<p id="error">We could not confirm your order. Please try again.</p>'}else{history.pushState({},'', '/success');document.getElementById('result').innerHTML='<h2>Order confirmed</h2>'}}}</script></body></html>`);
  });
  server.listen(port, '127.0.0.1', () => console.log(`Demo storefront: http://127.0.0.1:${port} (${fixed ? 'corrected' : 'intentionally faulty'})`)); return server;
}
if (process.argv[1]?.replaceAll('\\', '/').endsWith('/demo-app/server.ts')) startDemo();
