import { useEffect, useRef, useState } from 'react';
import { Copy, Download, X } from 'lucide-react';
import type { HandoffTarget } from '../../../packages/core/src/understanding.ts';
import { api } from './api';

export function CopyContext({ kind, id }: HandoffTarget) {
  const [open, setOpen] = useState(false), [text, setText] = useState(''), [goal, setGoal] = useState(''), [source, setSource] = useState(true), [message, setMessage] = useState(''), [loading, setLoading] = useState(false);
  const dialog = useRef<HTMLDialogElement>(null);
  useEffect(() => { if (!open) return; dialog.current?.showModal(); let live = true; setLoading(true); setText(''); setMessage(''); api<{text: string}>('/handoff', 'POST', { kind, id, includeSource: source }).then(r => { if (live) setText(r.text); }).catch(e => { if (live) setMessage(e.message); }).finally(() => { if (live) setLoading(false); }); return () => { live = false; }; }, [open, kind, id, source]);
  const payload = (goal.trim() ? `User request:\n${goal.trim()}\n\n` : '') + text;
  return <><button className="btn small-btn" onClick={() => setOpen(true)}><Copy size={14}/>Copy context for AI</button>{open && <dialog className="modal wide context-export" ref={dialog} aria-label="AI context handoff" onCancel={() => setOpen(false)}><header><div><h2>AI context handoff</h2><p>Review the context, then copy it into any AI tool. Nothing is sent automatically.</p></div><button className="icon-btn" aria-label="Close AI context" onClick={() => setOpen(false)}><X size={18}/></button></header><div className="form"><label>What should the AI help with? (optional)<textarea rows={2} value={goal} onChange={e => setGoal(e.target.value)} placeholder="Explain this behavior, implement a change, review the evidence, or continue my work…"/></label><label className="checkbox-label"><input type="checkbox" checked={source} onChange={e => setSource(e.target.checked)}/>Include relevant source excerpts</label><p className="form-hint">Includes selected evidence, project configuration, Git state, notes, reproduction details, and local artifact references. Source limits and unavailable evidence are listed. Images and traces must be attached separately when the AI cannot access your files.</p><label>Context preview<textarea aria-label="Context preview" readOnly rows={16} className="code-editor" value={loading ? 'Preparing local context…' : payload}/></label><div className="button-row"><button className="btn primary" disabled={!text || loading} onClick={async () => { try { await navigator.clipboard.writeText(payload); setMessage('Context copied. Paste it into your AI conversation.'); } catch { setMessage('Select the preview and copy it manually; clipboard access is unavailable.'); } }}><Copy size={15}/>Copy full context</button><button className="btn" disabled={!text || loading} onClick={() => { const url = URL.createObjectURL(new Blob([payload], { type: 'text/markdown;charset=utf-8' })); const link = document.createElement('a'); link.href = url; link.download = `dcr-${kind}-${id}.md`; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }}><Download size={15}/>Save Markdown</button></div>{message && <p role="status">{message}</p>}</div></dialog>}</>;
}
