import { useState } from 'react';
import { flowSchema } from '../../../packages/core/src/index.ts';
import { api } from './api';

const defaults: Record<string, any> = {
  goto: { url: '/' }, click: { role: 'button', name: '' }, fill: { label: '', env: 'DCR_INPUT_1' },
  select: { label: '', env: 'DCR_CHOICE_1' }, check: { label: '', checked: true }, upload: { label: '', env: 'DCR_UPLOAD_1' },
  assertText: { text: '' }, back: {}, forward: {}, reload: {}, newTab: { name: 'tab2', url: '/' },
  switchTab: { name: 'main' }, closeTab: {}, popup: { role: 'link', name: '', popupTab: 'popup1' },
};
export function FlowEditor({ initial, busy, onSave }: { initial?: any; busy: boolean; onSave: (flow: unknown) => void }) {
  const [flow, setFlow] = useState<any>(initial || { name: 'My first flow', description: '', steps: [{ action: 'goto', url: '/' }, { action: 'assertText', text: 'Welcome' }] });
  const [error, setError] = useState(''), [diagnostics, setDiagnostics] = useState<string[]>([]), [reviewed, setReviewed] = useState(false);
  const [json, setJson] = useState<string | null>(null);
  const update = (index: number, step: any) => setFlow({ ...flow, steps: flow.steps.map((s: any, i: number) => i === index ? step : s) });
  const move = (index: number, delta: number) => { const steps = [...flow.steps]; [steps[index], steps[index + delta]] = [steps[index + delta], steps[index]]; setFlow({ ...flow, steps }); };
  return <form className="form" onSubmit={e => { e.preventDefault(); try { if (diagnostics.length && !reviewed) throw new Error('Review the import warnings first'); const value = flowSchema.parse(json === null ? flow : JSON.parse(json)); setError(''); onSave(value); } catch (e) { setError(e instanceof Error ? e.message : 'Invalid flow'); } }}>
    <label>Import JSON or a Playwright test<input type="file" accept=".json,.ts,.js,.mjs" onChange={async e => { try { const file = e.target.files?.[0]; if (!file) return; if (file.size > 200000) throw new Error('Import is limited to 200 KB'); const text = await file.text(); const result = file.name.endsWith('.json') ? { flow: flowSchema.parse(JSON.parse(text)), diagnostics: [] } : await api<any>('/flows/import', 'POST', { source: text }); setFlow(result.flow); setDiagnostics(result.diagnostics); setReviewed(false); setJson(null); setError(''); } catch (e) { setError(String(e)); } }}/></label>
    {diagnostics.length > 0 && <div className="alert warning"><div><b>Some script behavior needs manual conversion</b><ul>{diagnostics.map((d, i) => <li key={i}>{d}</li>)}</ul><label className="checkbox-label"><input type="checkbox" checked={reviewed} onChange={e => setReviewed(e.target.checked)}/>I reviewed these gaps and adjusted the steps below.</label></div></div>}
    <div className="button-row"><button type="button" className="btn" onClick={() => { try { if (json === null) setJson(JSON.stringify(flow, null, 2)); else { setFlow(flowSchema.parse(JSON.parse(json))); setJson(null); } } catch (e) { setError(String(e)); } }}>{json === null ? 'Edit JSON' : 'Visual editor'}</button></div>
    {json !== null ? <label>Flow JSON<textarea className="code-editor" rows={18} value={json} onChange={e => setJson(e.target.value)}/></label> : <>
      <label>Flow name<input required maxLength={120} value={flow.name} onChange={e => setFlow({ ...flow, name: e.target.value })}/></label>
      <label>Description<input maxLength={500} value={flow.description} onChange={e => setFlow({ ...flow, description: e.target.value })}/></label>
      {flow.steps.map((step: any, index: number) => <fieldset className="flow-step" key={index}><legend>Step {index + 1}</legend><div className="form-columns"><label>Action<select value={step.action} onChange={e => update(index, { action: e.target.value, ...defaults[e.target.value] })}>{Object.keys(defaults).map(action => <option key={action}>{action}</option>)}</select></label>
        {Object.keys(defaults[step.action] || {}).filter(key => key !== 'env').map(key => <label key={key}>{key === 'name' && step.action === 'switchTab' ? 'Tab name' : key}{key === 'checked' ? <select value={String(step.checked)} onChange={e => update(index, { ...step, checked: e.target.value === 'true' })}><option value="true">Checked</option><option value="false">Unchecked</option></select> : key === 'role' ? <select value={step.role} onChange={e => update(index, { ...step, role: e.target.value })}>{['button', 'link', ...(step.action === 'click' ? ['checkbox'] : [])].map(role => <option key={role}>{role}</option>)}</select> : <input required value={step[key] || ''} onChange={e => update(index, { ...step, [key]: e.target.value })}/>}</label>)}
        {['fill', 'select', 'upload'].includes(step.action) && <><label>Input source<select value={step.env !== undefined ? 'env' : 'value'} onChange={e => { const next = { ...step }; delete next.env; delete next.value; next[e.target.value] = ''; update(index, next); }}><option value="env">Environment variable</option>{step.action !== 'upload' && <option value="value">Literal value</option>}</select></label><label>{step.env !== undefined ? 'Environment variable name' : 'Value'}<input value={step.env ?? step.value ?? ''} onChange={e => update(index, { ...step, [step.env !== undefined ? 'env' : 'value']: e.target.value })}/></label></>}
      </div><details><summary>Locator, tab and iframe options</summary><label className="checkbox-label"><input type="checkbox" checked={step.exact ?? true} onChange={e => update(index, { ...step, exact: e.target.checked })}/>Match accessible names exactly</label>{step.action === 'select' && <label>Dropdown selector (optional, recorded when label includes option text)<input value={step.selector || ''} onChange={e => update(index, { ...step, selector: e.target.value || undefined })}/></label>}<div className="form-columns"><label>Tab (blank uses current)<input placeholder="main" value={step.tab || ''} onChange={e => update(index, { ...step, tab: e.target.value || undefined })}/></label><label>Iframe selectors, outermost first<textarea rows={2} value={(step.frames || []).join('\n')} onChange={e => update(index, { ...step, frames: e.target.value.split('\n').filter(Boolean) })}/></label></div></details><div className="button-row"><button type="button" className="btn" disabled={!index} onClick={() => move(index, -1)} aria-label={`Move step ${index + 1} up`}>Move up</button><button type="button" className="btn" disabled={index === flow.steps.length - 1} onClick={() => move(index, 1)} aria-label={`Move step ${index + 1} down`}>Move down</button><button type="button" className="btn" onClick={() => setFlow({ ...flow, steps: flow.steps.filter((_: any, i: number) => i !== index) })}>Remove</button></div></fieldset>)}
      <button type="button" className="btn" disabled={flow.steps.length >= 100} onClick={() => setFlow({ ...flow, steps: [...flow.steps, { action: 'assertText', text: '' }] })}>Add step</button>
    </>}
    <p className="form-hint">Uploads use an environment variable pointing to a file inside the project (up to 20 MB). Imported scripts are parsed into steps; unsupported code is reported for review.</p>
    {error && <p role="alert" className="red-text">{error}</p>}<button className="btn primary" disabled={busy || !!diagnostics.length && !reviewed}>Save flow</button>
  </form>;
}
