import { FlowEditor } from './FlowEditor';
import { useEffect, useState } from 'react';
import type { Project } from '../../../packages/core/src/index.ts';
import { api } from './api';
export function RecorderPanel({ project, perform, busy }: { project: Project; perform: (job: () => Promise<void>) => void; busy: boolean }) {
  const [recording, setRecording] = useState(''), [route, setRoute] = useState('/'), [draft, setDraft] = useState(''), [warnings, setWarnings] = useState<string[]>([]);
  const [tab, setTab] = useState('main');
  useEffect(() => { void api<{ id: string; projectId: string }[]>('/recordings').then(sessions => setRecording(sessions.find(session => session.projectId === project.id)?.id || '')).catch(() => {}); }, [project.id]);
  return <section className="panel content-panel"><h2>Record a browser flow</h2><p className="muted-text">A browser opens for your clicks, labeled inputs and checkboxes. Review the recorded steps before saving. Typed values become environment references.</p><div className="form-columns"><label>Starting route<input value={route} onChange={e => setRoute(e.target.value)} disabled={!!recording}/></label><div className="button-row">{!recording ? <button className="btn" disabled={busy} onClick={() => perform(async () => { const result = await api<{ id: string }>(`/projects/${project.id}/recordings`, 'POST', { route }); setRecording(result.id); setDraft(''); })}>Start recording</button> : <button className="btn primary" disabled={busy} onClick={() => perform(async () => { const result = await api<any>(`/recordings/${recording}/stop`, 'POST'); setRecording(''); setDraft(JSON.stringify(result.flow, null, 2)); setWarnings(result.warnings); })}>Stop and review</button>}</div></div>{recording && <div className="form"><p role="status">Recording in the browser window. Use these controls to record navigation.</p><label>Tab name<input value={tab} onChange={e => setTab(e.target.value)}/></label><label>Navigation URL<input value={route} onChange={e => setRoute(e.target.value)}/></label><div className="button-row">{['back', 'forward', 'reload', 'goto', 'newTab', 'switchTab'].map(action => <button className="btn" key={action} disabled={busy} onClick={() => perform(async () => { const result = await api<any>(`/recordings/${recording}/navigate`, 'POST', { action, url: route, tab }); if (action === 'newTab') setTab(result.tabs.at(-1)); })}>{action}</button>)}</div><small>First tab: main. Additional tabs: tab2, tab3?</small></div>}{draft && <><ul>{warnings.map(warning => <li key={warning}>{warning}</li>)}</ul><FlowEditor initial={JSON.parse(draft)} busy={busy} onSave={flow => perform(async () => { await api(`/projects/${project.id}/flows`, 'POST', flow); setDraft(''); })}/></>}</section>;
}
