import { useState, type FormEvent } from 'react';
import { ArrowRight, Check, CreditCard, Download, Edit3, FlaskConical, Network, Play, Plus, ShieldCheck, X } from 'lucide-react';
import type { Flow, Project, Run } from '../../../packages/core/src/index.ts';
import { mutationKinds, paymentCases, type ApiFixture, type Matrix, type Scenario } from '../../../packages/core/src/reliability.ts';
import { api } from './api';

type Props = { kind: 'api' | 'payment'; project?: Project; flows: Flow[]; fixtures: ApiFixture[]; scenarios: Scenario[]; matrices: Matrix[]; runs: Run[]; busy: boolean; perform: (action: () => Promise<void>) => void; openRun: (run: Run) => void; onSettings: () => void };
export function ScenarioEvidence({ run }: { run: Run }) {
  if (!run.result) return null;
  return <section className="panel content-panel scenario-evidence"><div className="section-heading"><h2>{run.scenario.name}</h2><span className="badge">{run.scenario.kind} · v{run.scenario.version}{run.result.matchedRequests !== undefined ? ` · ${run.result.matchedRequests} request(s) mutated` : ''}</span></div><div className="finding-comparison"><div><label>EXPECTED</label><pre>{typeof run.result.expected === 'string' ? run.result.expected : JSON.stringify(run.result.expected, null, 2)}</pre></div><div><label>OBSERVED</label><pre>{typeof run.result.observed === 'string' ? run.result.observed : JSON.stringify(run.result.observed, null, 2)}</pre></div></div></section>;
}
export function ReliabilityPanel({ kind, project, flows, fixtures, scenarios, matrices, runs, busy, perform, openRun, onSettings }: Props) {
  const [editor, setEditor] = useState<'capture' | 'fixture' | 'scenario' | ''>('');
  const [editingScenario, setEditingScenario] = useState<Scenario>();
  const [editingFixture, setEditingFixture] = useState<ApiFixture>();
  const [selected, setSelected] = useState<string[]>([]), [confirmed, setConfirmed] = useState(false);
  const [formError, setFormError] = useState('');
  if (!project) return <div className="panel content-panel"><h2>Choose a project to open this lab</h2><p className="muted-text">Select a project above. Its allowlist, fixtures, and scenario results stay together.</p></div>;
  const available = project.config.modules.includes(kind === 'api' ? 'api' : 'payments');
  const cases = scenarios.filter(s => s.projectId === project.id && s.definition.kind === kind);
  const projectFixtures = fixtures.filter(f => f.projectId === project.id);
  const projectFlows = flows.filter(f => f.projectId === project.id);
  const demo = project.path.replaceAll('\\', '/').endsWith('/examples/demo-app');
  const latestMatrix = matrices.find(m => m.projectId === project.id && m.scenarioIds.some(id => cases.some(s => s.id === id)));
  const matrixRuns = latestMatrix?.runIds.map(id => runs.find(run => run.id === id)).filter((run): run is Run => Boolean(run)) || [];
  const selectedIds = selected.filter(id => cases.some(s => s.id === id));
  const submit = (event: FormEvent<HTMLFormElement>, action: (fields: Record<string, FormDataEntryValue>) => Promise<void>) => {
    event.preventDefault(); const fields = Object.fromEntries(new FormData(event.currentTarget)); setFormError('');
    perform(async () => { try { await action(fields); setEditor(''); } catch (error) { setFormError(String(error)); throw error; } });
  };
  return <div className="reliability-lab">
    <section className="panel lab-intro"><span className={`feature-icon ${kind === 'api' ? 'blue-bg' : 'mint-bg'}`}>{kind === 'api' ? <Network size={24}/> : <CreditCard size={24}/>}</span><div><h2>{kind === 'api' ? 'Make the unexpected repeatable.' : 'A success screen is only half the story.'}</h2><p>{kind === 'api' ? 'Capture a sanitized response, change one condition, and watch how your flow responds.' : 'Check browser history, refresh, and duplicate events against the fixture server’s authoritative state.'}</p></div><span className="badge">PHASE 2</span></section>
    {demo && !available && <section className="panel content-panel"><h2>Set up the included reliability fixtures</h2><p className="muted-text">Adds seven API cases and three payment cases. The included fixture server never contacts a payment gateway.</p><label className="checkbox-label"><input type="checkbox" checked={confirmed} onChange={e => setConfirmed(e.target.checked)}/>I confirm this is the included local test app and all payment operations use fixtures.</label><button className="btn primary" disabled={!confirmed || busy} onClick={() => perform(async () => { await api(`/projects/${project.id}/setup-labs`, 'POST', { confirmFixtures: true }); })}><FlaskConical size={16}/>Configure demo labs</button></section>}
    {!available ? <section className="panel content-panel"><h2>Enable this module for this project</h2><p className="muted-text">{kind === 'api' ? 'Add “api” to modules and exact endpoint paths to reliability.apiPaths in project settings.' : 'Add “payments” to modules and explicitly confirm the test environment and fixture-only adapter in reliability.payment.'}</p><button className="btn" onClick={onSettings}>Project settings<ArrowRight size={15}/></button></section> : <>
    <div className="lab-safety"><ShieldCheck size={16}/>{kind === 'api' ? <span>Exact allowed paths: <code>{project.config.reliability.apiPaths.join(', ') || 'none configured'}</code> · Auth and payment endpoints are excluded.</span> : <span>Fixture HTTP adapter · Test environment {project.config.reliability.payment.testEnvironmentConfirmed ? 'confirmed' : 'not confirmed'} · Fresh isolated order for every run.</span>}</div>
    {kind === 'api' && <section className="panel content-panel"><div className="section-heading"><h2>Response fixtures <span className="count">{projectFixtures.length}</span></h2><div className="button-row"><button className="btn" onClick={() => { setEditor('fixture'); setEditingFixture(undefined); setFormError(''); }}><Plus size={14}/>Import JSON</button><button className="btn" disabled={!projectFlows.length} onClick={() => { setEditor('capture'); setFormError(''); }}><Download size={14}/>Capture from flow</button></div></div>{!projectFixtures.length && <p className="muted-text">Capture a GET fetch/XHR response through a flow, or import a JSON fixture.</p>}<div className="fixture-list">{projectFixtures.map(f => <div className="fixture-row" key={f.id}><Network size={17}/><div><b>{f.name}</b><small>{f.method} {new URL(f.url).pathname} · v{f.version} · {f.sourceRunId ? 'browser capture' : 'imported fixture'}</small></div>{f.sourceRunId && runs.find(r => r.id === f.sourceRunId) && <button className="text-btn" onClick={() => openRun(runs.find(r => r.id === f.sourceRunId)!)}>Capture evidence</button>}<button className="icon-btn" aria-label={`Edit ${f.name}`} onClick={() => { setEditor('fixture'); setEditingFixture(f); setFormError(''); }}><Edit3 size={16}/></button></div>)}</div></section>}
    {editor && <section className="panel content-panel lab-editor"><div className="section-heading"><h2>{editor === 'capture' ? 'Capture a selected response' : editor === 'fixture' ? `${editingFixture ? 'Edit' : 'Import'} JSON fixture` : `${editingScenario ? 'Edit' : 'Create'} scenario`}</h2><button className="icon-btn" aria-label="Close editor" onClick={() => setEditor('')}><X size={18}/></button></div>{formError && <p className="red-text" role="alert">{formError}</p>}
      {editor === 'capture' && <form className="form" onSubmit={e => submit(e, async fields => { const run = await api<Run>(`/projects/${project.id}/capture`, 'POST', fields); openRun(run); })}><div className="form-columns"><label>Fixture name<input name="name" required defaultValue="Captured response"/></label><label>Flow<select name="flowId">{projectFlows.map(f => <option key={f.id} value={f.id}>{f.name}</option>)}</select></label></div><label>Exact response URL<input name="url" type="url" required defaultValue={new URL(project.config.reliability.apiPaths[0] || '/api/products', project.baseUrl).href}/></label><p className="form-hint">This explicitly captures only the selected successful JSON response (up to 64 KB). The flow must make a GET fetch/XHR request to this exact URL.</p><button className="btn primary" disabled={busy}><Play size={15}/>Run flow and capture</button></form>}
      {editor === 'fixture' && <form key={editingFixture?.id || 'new'} className="form" onSubmit={e => submit(e, async fields => { await api(editingFixture ? `/fixtures/${editingFixture.id}` : `/projects/${project.id}/fixtures`, editingFixture ? 'PUT' : 'POST', { name: fields.name, url: fields.url, json: JSON.parse(String(fields.json)), status: Number(fields.status) }); })}><div className="form-columns"><label>Name<input name="name" required defaultValue={editingFixture?.name || 'API fixture'}/></label><label>Original status<input name="status" type="number" min={200} max={299} defaultValue={editingFixture?.status || 200}/></label></div><label>Exact GET endpoint URL<input name="url" type="url" required defaultValue={editingFixture?.url || new URL(project.config.reliability.apiPaths[0] || '/api/products', project.baseUrl).href}/></label><label>Response JSON<textarea name="json" className="code-editor" rows={9} required defaultValue={JSON.stringify(editingFixture?.json || { items: [] }, null, 2)}/></label><p className="form-hint">Saved fixtures are redacted. Existing scenario and run snapshots stay unchanged; edit a scenario to use this fixture revision.</p><button className="btn primary" disabled={busy}><Check size={15}/>Save fixture</button></form>}
      {editor === 'scenario' && <ScenarioEditor key={editingScenario?.id || 'new'} kind={kind} scenario={editingScenario} flows={projectFlows} fixtures={projectFixtures} busy={busy} onSubmit={e => submit(e, async fields => { const data = kind === 'api' ? { kind, name: fields.name, flowId: fields.flowId, fixtureId: fields.fixtureId, expectedText: fields.expectedText, mutation: { kind: fields.mutation, pointer: fields.pointer, delayMs: Number(fields.delayMs), stringLength: Number(fields.stringLength) } } : { kind, name: fields.name, flowId: fields.flowId, paymentCase: fields.paymentCase }; await api(editingScenario ? `/scenarios/${editingScenario.id}` : `/projects/${project.id}/scenarios`, editingScenario ? 'PUT' : 'POST', data); })}/>}
    </section>}
    <section className="section"><div className="section-heading"><h2>Scenario cases <span className="count">{cases.length}</span></h2><button className="btn" disabled={!projectFlows.length || kind === 'api' && !projectFixtures.length} onClick={() => { setEditingScenario(undefined); setEditor('scenario'); setFormError(''); }}><Plus size={15}/>New scenario</button></div><div className="scenario-grid">{cases.map(s => { const last = runs.find(run => run.projectId === project.id && run.scenario.name === s.definition.name && run.scenario.kind === kind); return <article className="panel scenario-card" key={s.id}><div className="scenario-title"><input aria-label={`Select ${s.definition.name}`} type="checkbox" checked={selectedIds.includes(s.id)} onChange={e => setSelected(e.target.checked ? [...selectedIds, s.id] : selectedIds.filter(id => id !== s.id))}/><h3>{s.definition.name}</h3><span className="badge">v{s.definition.version}</span></div><p>{s.definition.kind === 'api' ? `${s.definition.mutation.kind} · ${s.definition.mutation.pointer || 'response'}` : s.definition.kind === 'payment' ? s.definition.paymentCase : ''}</p><div className="scenario-expectation"><small>EXPECTED</small><span>{s.definition.kind === 'api' ? s.definition.expectedText : 'Confirmed in browser and server · confirmation count 1'}</span></div><footer>{last ? <button className={`text-btn ${last.status === 'failed' ? 'red-text' : 'mint'}`} onClick={() => openRun(last)}>{last.status}<ArrowRight size={13}/></button> : <small className="muted-text">Not run yet</small>}<div className="button-row"><button className="icon-btn" aria-label={`Edit ${s.definition.name}`} onClick={() => { setEditingScenario(s); setEditor('scenario'); setFormError(''); }}><Edit3 size={14}/></button><button className="btn small-btn" disabled={busy} onClick={() => perform(async () => openRun(await api<Run>(`/scenarios/${s.id}/run`, 'POST')))}><Play size={13}/>Run case</button></div></footer></article>; })}</div>{!cases.length && <div className="panel content-panel"><p className="muted-text">Create a scenario using a saved flow. Every case produces a normal run with its own evidence and replay command.</p></div>}</section>
    <section className="panel content-panel"><div className="section-heading"><h2>Run a matrix</h2><button className="text-btn" onClick={() => setSelected(selectedIds.length === cases.length ? [] : cases.map(s => s.id))}>{selectedIds.length === cases.length ? 'Clear selection' : 'Select all cases'}</button></div><p className="muted-text">{selectedIds.length} selected. Each case uses a fresh browser context and retains its own scenario snapshot.</p><button className="btn primary" disabled={!selectedIds.length || busy || latestMatrix?.status === 'running'} onClick={() => perform(async () => { await api(`/projects/${project.id}/matrices`, 'POST', { name: kind === 'api' ? 'API response matrix' : 'Payment stress matrix', scenarioIds: selectedIds }); })}><Play size={15}/>Run selected cases</button>{latestMatrix && <div className="matrix-results"><div className="matrix-summary"><b>{latestMatrix.name}</b><span>{latestMatrix.status} · {latestMatrix.runIds.length}/{latestMatrix.scenarioIds.length} started · {matrixRuns.filter(r => r.status === 'passed').length} passed · {matrixRuns.filter(r => r.status === 'failed').length} failed</span></div>{latestMatrix.error && <p className="red-text">{latestMatrix.error}</p>}{matrixRuns.map(run => <button className="matrix-row" key={run.id} onClick={() => openRun(run)}><span>{run.scenario.name}</span><b className={run.status === 'failed' ? 'red-text' : run.status === 'passed' ? 'mint' : 'muted-text'}>{run.status}</b><ArrowRight size={14}/></button>)}</div>}</section>
    </>}
  </div>;
}

function ScenarioEditor({ kind, scenario, flows, fixtures, busy, onSubmit }: { kind: 'api' | 'payment'; scenario?: Scenario; flows: Flow[]; fixtures: ApiFixture[]; busy: boolean; onSubmit: (e: FormEvent<HTMLFormElement>) => void }) {
  const definition = scenario?.definition, mutation = definition?.kind === 'api' ? definition.mutation : undefined;
  return <form className="form" onSubmit={onSubmit}><div className="form-columns"><label>Scenario name<input name="name" required defaultValue={definition?.name || ''} placeholder={kind === 'api' ? 'Empty list' : 'Back after success'}/></label><label>Flow<select name="flowId" defaultValue={scenario?.flowId}>{flows.map(f => <option key={f.id} value={f.id}>{f.name}</option>)}</select></label></div>{kind === 'api' ? <><div className="form-columns"><label>Response fixture<select name="fixtureId" defaultValue={scenario?.fixtureId}>{fixtures.map(f => <option key={f.id} value={f.id}>{f.name} · v{f.version}</option>)}</select></label><label>Mutation<select name="mutation" defaultValue={mutation?.kind || 'empty-list'}>{mutationKinds.map(k => <option key={k}>{k}</option>)}</select></label></div><label>JSON Pointer<input name="pointer" defaultValue={mutation?.pointer ?? '/items'} placeholder="/items or /items/0/subtitle"/><small>Use an empty pointer for the root. Status and delay mutations ignore this field.</small></label><div className="form-columns"><label>Delay (ms)<input name="delayMs" type="number" min={1} max={5000} defaultValue={mutation?.delayMs || 800}/></label><label>Oversized string length<input name="stringLength" type="number" min={1} max={16000} defaultValue={mutation?.stringLength || 4096}/></label></div><label>Expected visible text<input name="expectedText" required defaultValue={definition?.kind === 'api' ? definition.expectedText : 'No products yet'}/></label></> : <><label>Stress scenario<select name="paymentCase" defaultValue={definition?.kind === 'payment' ? definition.paymentCase : paymentCases[0]}>{paymentCases.map(k => <option key={k}>{k}</option>)}</select></label><p className="form-hint">The flow must complete one fixture confirmation. Use {'{orderId}'} in its navigation URL. Then the case checks browser text and authoritative state with confirmationCount = 1.</p></>}<button className="btn primary" disabled={busy}><Check size={15}/>Save scenario</button></form>;
}
