import { useState } from 'react';
import { ArrowRight, Check, FileCode2, Play, RefreshCw } from 'lucide-react';
import type { Project, Run, Task } from '../../../packages/core/src/index.ts';
import type { Report, SessionSnapshot, SourceLink } from '../../../packages/core/src/understanding.ts';
import { api } from './api';
import { CopyContext } from './CopyContext';

export function SourceLinks({ projectId, sources, onSource }: { projectId: string; sources: SourceLink[]; onSource: (projectId: string, file: string) => void }) {
  return <div className="source-links">{sources.map((source, i) => <div key={i}><button className="text-btn" onClick={() => onSource(projectId, source.file)}><FileCode2 size={15}/>{source.file}{source.line ? `:${source.line}` : ''}</button><small>{source.provenance} · {source.component || source.reason}</small></div>)}</div>;
}
export function ReportView({ report, onSource, perform }: { report: Report; onSource: (projectId: string, file: string) => void; perform: (f: () => Promise<void>) => void }) {
  const data = report.data;
  const [dispositions, setDispositions] = useState<Record<string, string>>({});
  const dispose = (findingId: string, disposition: string) => perform(async () => { await api(`/findings/${findingId}`, 'PATCH', { disposition }); setDispositions({ ...dispositions, [findingId]: disposition }); });
  return <section className="panel content-panel report-view"><div className="section-heading"><div><h2>{report.name}</h2><small>{new Date(report.createdAt).toLocaleString()} · saved evidence</small></div><CopyContext kind="report" id={report.id}/></div>
    {report.kind === 'risk' && <><p className="muted-text">{data.comparison}. Base: {data.base} ({data.baseCommit.slice(0, 8)})</p><div className="report-columns"><section><h3>Directly changed <span className="badge">Git</span></h3>{data.changed.map((file: string) => <button key={file} className="source-row text-btn" onClick={() => onSource(report.projectId, file)}>{file}</button>)}{!data.changed.length && <p>No changes against this base.</p>}</section><section><h3>Dependent files <span className="badge">Static</span></h3>{data.dependents.map((d: any) => <div key={d.file}><button className="text-btn" onClick={() => onSource(report.projectId, d.file)}>{d.file}</button><small>{d.reason}</small><details><summary>Import evidence</summary><pre>{JSON.stringify(d.edges, null, 2)}</pre></details></div>)}</section></div><h3>Affected routes</h3>{data.routes.map((r: any, i: number) => <div className="report-row" key={i}><b>{r.path}</b><span className="badge">{r.provenance}</span><button className="text-btn" onClick={() => onSource(report.projectId, r.file)}>{r.file}</button><small>{r.reason} · {r.observedRuns.length} run(s) observed navigating here</small></div>)}<h3>Related tests</h3>{data.tests.map((t: any) => <div className="report-row" key={t.file}><button className="text-btn" onClick={() => onSource(report.projectId, t.file)}>{t.file}</button><span className="badge">{t.provenance}</span><small>{t.reason}</small></div>)}<h3>Coverage gaps</h3><ul>{data.gaps.map((g: string) => <li key={g}>{g}</li>)}</ul></>}
    {report.kind === 'element' && <><div className="finding-comparison"><div><label>OBSERVED ELEMENT</label><p>{data.tag} · {data.selector}</p><p>{data.text}</p><code>{data.route}</code></div><div><label>SOURCE CONFIDENCE</label><p>{data.sourceConfidence}</p><SourceLinks projectId={report.projectId} sources={report.sources} onSource={onSource}/></div></div><div className="report-columns"><section><h3>DOM attributes</h3><pre>{JSON.stringify(data.attributes, null, 2)}</pre></section><section><h3>Computed styles</h3><pre>{JSON.stringify(data.styles, null, 2)}</pre></section></div>{data.react && <><h3>React owners and state</h3><pre>{JSON.stringify(data.react, null, 2)}</pre>{data.reactAfter && <><h3>React after interaction</h3><pre>{JSON.stringify(data.reactAfter, null, 2)}</pre></>}</>}{data.instrumentation && <><h3>Application-supplied labels</h3><pre>{JSON.stringify(data.instrumentation, null, 2)}</pre></>}<>{data.interactions?.length > 0 && <><h3>Explicitly instrumented interactions</h3><pre>{JSON.stringify(data.interactions, null, 2)}</pre></>}</><ul>{data.limitations.map((s: string) => <li key={s}>{s}</li>)}</ul></>}
    {report.kind === 'drift' && <><p>{data.note}</p>{data.gaps.map((g: string) => <p className="form-hint" key={g}>{g}</p>)}{!data.findings.length && <p className="mint">All matched elements are within the configured token values and tolerances.</p>}{data.findings.map((f: any) => <article className="finding-card panel" key={f.fingerprint}><div className="section-heading"><h3>{f.rule} · {f.property}</h3><span className="badge">{dispositions[f.findingId] || f.disposition || f.status}</span></div><div className="finding-comparison"><div><label>EXPECTED TOKENS</label><pre>{JSON.stringify(f.expected, null, 2)}</pre><small>Tolerance: {f.tolerance}px</small></div><div><label>OBSERVED</label><p>{f.observed}</p><code>{f.route}</code><pre>{f.selectors.join('\n')}</pre></div></div><SourceLinks projectId={report.projectId} sources={f.sources} onSource={onSource}/><footer><CopyContext kind="finding" id={f.findingId}/><button className="text-btn" onClick={() => dispose(f.findingId, 'intentional')}>Accept as intentional</button><button className="text-btn" onClick={() => dispose(f.findingId, 'suppressed')}>Suppress this outlier</button><button className="text-btn" onClick={() => dispose(f.findingId, 'open')}>Reopen</button></footer></article>)}</>}
    {report.kind !== 'risk' && <div className="report-captures"><h3>Highlighted browser evidence</h3>{report.artifactIds.slice(0, -1).map((id, i) => <a href={`/api/artifacts/${id}`} key={id} target="_blank" rel="noreferrer"><img style={{ width: '100%', borderRadius: 8, marginBottom: 16 }} src={`/api/artifacts/${id}`} alt={`Highlighted ${report.kind} inspection, page ${i + 1}`}/></a>)}</div>}<div className="report-artifacts">{report.artifactIds.map((id, i) => <a key={id} className="btn" href={`/api/artifacts/${id}`} target="_blank" rel="noreferrer">{i === report.artifactIds.length - 1 ? 'Download report JSON' : `Open screenshot ${i + 1}`} <ArrowRight size={14}/></a>)}</div><details><summary>Full structured evidence</summary><pre>{JSON.stringify(data, null, 2)}</pre></details>
  </section>;
}
type Props = { page: string; project?: Project; reports: Report[]; sessions: SessionSnapshot[]; runs: Run[]; tasks: Task[]; notes: {projectId: string; text: string; nextStep: string}[]; busy: boolean; perform: (f: () => Promise<void>) => void; onSource: (projectId: string, file: string) => void; onRun: (run: Run) => void; onTask: (task: Task) => void; onSettings: () => void };
const sampleRules = [{ name: 'Primary button', selector: 'button.primary', property: 'background-color', values: ['var(--color-primary)'], tolerance: 0 }, { name: 'Card spacing', selector: '.demo-card', property: 'padding-top', values: ['var(--space-card)'], tolerance: 1 }];
export function UnderstandingPanel(props: Props) {
  const { page, project, reports, sessions, tasks, runs, notes, perform, onSource, onRun, onTask, busy } = props;
  const [chosen, setChosen] = useState<Report>(), [rules, setRules] = useState(JSON.stringify(project?.config.understanding.driftRules.length ? project.config.understanding.driftRules : sampleRules, null, 2));
  const kind = page === 'UI Drift' ? 'drift' : page === 'Element Inspector' ? 'why' : page === 'Risk Map' ? 'risk' : 'context';
  if (!project) return <section className="panel content-panel"><h2>Choose a project</h2><p>Select a project above to inspect it or resume your work.</p></section>;
  if (!project.config.modules.includes(kind)) return <section className="panel content-panel"><h2>Enable {page}</h2><p>This module is disabled for this project.</p><button className="btn primary" onClick={() => perform(async () => { await api(`/projects/${project.id}/config`, 'PUT', { ...project.config, modules: [...project.config.modules, kind] }); })}>Enable module</button></section>;
  const history = reports.filter(r => r.projectId === project.id && r.kind === (kind === 'why' ? 'element' : kind));
  const current = chosen || history[0];
  const session = sessions.find(s => s.projectId === project.id), note = notes.find(n => n.projectId === project.id);
  if (kind === 'context') return <div className="continuity-grid"><section className="panel content-panel"><div className="section-heading"><h2>Your next session starts here</h2><CopyContext kind={session ? 'session' : 'project'} id={session?.id || project.id}/></div><p className="muted-text">Save your exact next step and task. Git activity is evidence; the suggested action is editable.</p><form key={session?.id || 'new'} className="form" onSubmit={e => { e.preventDefault(); const data = Object.fromEntries(new FormData(e.currentTarget)); perform(async () => { await api(`/projects/${project.id}/session`, 'POST', data); }); }}><label>Pinned note<textarea name="note" rows={4} defaultValue={note?.text ?? session?.note}/></label><label>Exact next step<input name="nextStep" defaultValue={note?.nextStep ?? session?.nextStep}/></label>{session?.proposedAction && <p className="form-hint">Suggested, not inferred intent: {session.proposedAction} Use this only if it matches your plan.</p>}<label>Suggested action (edit or clear)<input name="proposedAction" defaultValue={session?.proposedAction || ""}/></label><label>Resume task<select name="taskId" defaultValue={session?.taskId || ''}><option value="">No task selected</option>{tasks.filter(t => t.projectId === project.id).map(t => <option value={t.id} key={t.id}>{t.name}</option>)}</select></label><button className="btn primary" disabled={busy}><Check size={15}/>Save session snapshot</button></form>{session?.taskId && tasks.find(t => t.id === session.taskId) && <button className="btn full" onClick={() => onTask(tasks.find(t => t.id === session.taskId)!)}><Play size={15}/>Resume saved workspace</button>}{session?.lastFailedRunId && runs.find(r => r.id === session.lastFailedRunId) && <button className="btn full" onClick={() => onRun(runs.find(r => r.id === session.lastFailedRunId)!)}>Open saved failing flow<ArrowRight size={15}/></button>}</section><section className="panel content-panel"><h2>Saved Git context</h2>{session ? <><p>{new Date(session.createdAt).toLocaleString()}</p><dl><dt>Branch</dt><dd>{session.git.branch}</dd><dt>Commit</dt><dd>{session.git.commit}</dd><dt>Working tree</dt><dd>{session.git.dirty ? 'Uncommitted changes' : 'Clean'}</dd><dt>Open findings</dt><dd>{session.openFindingIds.length}</dd></dl><h3>Changed files</h3><pre>{session.git.files || 'None'}</pre><h3>Recent commits</h3><pre>{session.git.commits || 'No commits'}</pre></> : <p>Save a snapshot to preserve Git state, notes, runs, and the task to resume.</p>}</section></div>;
  return <><section className="panel content-panel"><div className="section-heading"><h2>{page}</h2><span className="badge">{kind === 'risk' ? 'Static analysis' : 'Browser evidence'}</span></div><form className="form" onSubmit={e => { e.preventDefault(); const data = Object.fromEntries(new FormData(e.currentTarget)); perform(async () => { const body = kind === 'drift' ? { routes: String(data.routes).split('\n').map(s => s.trim()).filter(Boolean), rules: JSON.parse(rules) } : kind === 'why' ? { ...data, interact: data.interact === 'on' } : data; setChosen(await api(`/projects/${project.id}/${kind === 'why' ? 'element' : kind}`, 'POST', body)); }); }}>
    {kind === 'risk' ? <label>Compare working tree against<input name="base" defaultValue="HEAD" required/><small>Git revision such as HEAD, main, or a commit hash. Includes staged and untracked changes.</small></label> : kind === 'drift' ? <><label>Routes (one per line)<textarea name="routes" rows={2} defaultValue="/design"/></label><label>Import token rules JSON<input type="file" accept=".json" onChange={e => { const file = e.target.files?.[0]; if (file) void file.text().then(setRules); }}/></label><label>Token rules<textarea aria-label="Token rules" className="code-editor" rows={9} value={rules} onChange={e => setRules(e.target.value)}/></label><p className="form-hint">Explicit values or CSS custom properties through var(--token). Numeric tolerances apply to pixel values. Use selectors to define button variants.</p></> : <><label>Page route<input name="route" defaultValue="/design" required/></label><label>Selected element (CSS selector)<input name="selector" defaultValue="#primary-button" required/></label><label className="checkbox-label"><input name="interact" type="checkbox"/>Click the selected element once and capture an instrumented interaction</label><p className="form-hint">Inspect a visible element by its selector. Source metadata is {project.config.understanding.bridgeEnabled ? 'enabled' : 'disabled'}. Uninstrumented elements still show DOM and computed style facts.</p><label className="checkbox-label"><input type="checkbox" checked={project.config.understanding.bridgeEnabled} onChange={e => { const enabled = e.target.checked; perform(async () => { await api(`/projects/${project.id}/config`, 'PUT', { ...project.config, understanding: { ...project.config.understanding, bridgeEnabled: enabled } }); }); }}/>Enable the opt-in source metadata bridge for this development project</label></>}
    <button className="btn primary" disabled={busy}><RefreshCw size={15}/>{busy ? 'Inspecting…' : kind === 'risk' ? 'Build risk map' : kind === 'drift' ? 'Scan selected routes' : 'Inspect element'}</button></form></section>{history.length > 0 && <label className="report-history">Saved reports<select aria-label="Saved reports" value={current?.id || ''} onChange={e => setChosen(history.find(r => r.id === e.target.value))}>{history.map(r => <option value={r.id} key={r.id}>{new Date(r.createdAt).toLocaleString()} · {r.name}</option>)}</select></label>}{current && <ReportView key={current.id} report={current} onSource={onSource} perform={perform}/>}</>;
}
