import type { CommandRun } from '../../../packages/modules/src/commands.ts';
import { api } from './api';
export function CommandOutput({ runs, perform }: { runs: CommandRun[]; perform: (job: () => Promise<void>) => void }) {
  return <section className="panel content-panel"><h2>Command output</h2>{!runs.length && <p className="muted-text">Launch a task command to see its status and output here.</p>}{runs.slice(0, 20).map(run => <details key={run.id} open={run.status === 'running'} className="command-output"><summary>{run.name} · {run.status} · {new Date(run.startedAt).toLocaleString()}{run.exitCode !== undefined && ` · exit ${run.exitCode}`}</summary>{run.status === 'running' && <button className="btn" onClick={() => perform(async () => { await api(`/commands/${run.id}/stop`, 'POST'); })}>Stop command</button>}<pre className="command-preview">{run.output || 'Waiting for a complete output line…'}</pre>{run.truncated && <p className="form-hint">Output was limited to 64 KB; oversized lines are omitted.</p>}</details>)}</section>;
}
export function ConfigurationControls({ text, onChange, onError }: { text: string; onChange: (text: string) => void; onError: (message: string) => void }) {
  let config: any; try { config = JSON.parse(text); } catch { return <p>Fix the configuration JSON to use these controls.</p>; }
  const update = (value: any) => { try { onChange(JSON.stringify({ ...config, ...value }, null, 2)); } catch { onError('Unable to update configuration'); } };
  return <><div className="form-columns"><label>Framework override<input placeholder="Automatic detection" value={config.detectionOverride?.framework || ''} onChange={e => update({ detectionOverride: { ...config.detectionOverride, framework: e.target.value || undefined } })}/></label><label>Package manager override<select value={config.detectionOverride?.packageManager || ''} onChange={e => update({ detectionOverride: { ...config.detectionOverride, packageManager: e.target.value || undefined } })}><option value="">Automatic detection</option>{['npm', 'pnpm', 'yarn', 'bun'].map(value => <option key={value}>{value}</option>)}</select></label></div><label className="checkbox-label"><input type="checkbox" checked={!!config.scheduledCleanup} onChange={e => update({ scheduledCleanup: e.target.checked })}/>Clean expired run evidence hourly while Control Room is open</label><label>Keep run evidence for (days)<input type="number" min={1} max={3650} value={config.retentionDays || 30} onChange={e => update({ retentionDays: Number(e.target.value) })}/></label><p className="form-hint">Active runs and runs referenced by matrices, captures, replays, or saved sessions are kept. Cleanup also runs when you save settings.</p><label className="checkbox-label"><input type="checkbox" checked={!!config.understanding?.reactInspection} onChange={e => update({ understanding: { ...config.understanding, reactInspection: e.target.checked } })}/>Inspect React component owners and state in element reports</label><p className="form-hint">React inspection reads bounded runtime values. Private elements and configured sensitive fields are excluded.</p></>;
}
