import assert from 'node:assert/strict';
import { mkdtempSync, cpSync, rmSync, mkdirSync, appendFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { once } from 'node:events';
import { execFileSync } from 'node:child_process';
import { chromium } from 'playwright';
import { Store } from '../packages/storage/src/index.ts';
import { ControlRoom } from '../packages/modules/src/service.ts';
import { startDemo } from '../examples/demo-app/server.ts';
import { startServer } from '../apps/service/src/server.ts';
import { handoff } from '../packages/modules/src/handoff.ts';
import type { Report, SessionSnapshot } from '../packages/core/src/understanding.ts';
import type { Finding } from '../packages/core/src/index.ts';

const root = mkdtempSync(join(tmpdir(), 'dcr-phase34-')), repo = join(root, 'repo');
cpSync(resolve('examples/demo-app'), repo, { recursive: true });
const git = (...args: string[]) => execFileSync('git', ['-C', repo, ...args], { stdio: 'ignore' });
git('init', '-b', 'main'); git('add', '.'); git('-c', 'user.name=Fixture', '-c', 'user.email=fixture@invalid.local', 'commit', '-m', 'baseline');
appendFileSync(join(repo, 'src/components/Button.tsx'), '\n// Shared change affecting both routes.\n');
let store = new Store(join(root, 'data')), service = new ControlRoom(store), demo: ReturnType<typeof startDemo> | undefined, dashboard: ReturnType<typeof startServer> | undefined;
let browser: Awaited<ReturnType<typeof chromium.launch>> | undefined;
const stopDemo = async () => { if (demo) { await new Promise<void>(resolve => demo!.close(() => resolve())); demo = undefined; } };
try {
  demo = startDemo(4418); await once(demo, 'listening');
  const project = service.addProject({ name: 'Understanding fixture', path: repo, baseUrl: 'http://127.0.0.1:4418', config: { modules: ['time-machine', 'tasks', 'drift', 'why', 'risk', 'context'], understanding: { bridgeEnabled: true, driftRules: [{ name: 'Primary button', selector: 'button.primary', property: 'background-color', values: ['var(--color-primary)'] }, { name: 'Card spacing', selector: '.demo-card', property: 'padding-top', values: ['var(--space-card)'], tolerance: 1 }] } } });
  const drift = await service.understanding.drift(project.id, { routes: ['/design'] });
  assert.equal(drift.data.findings.length, 2); assert.ok(drift.data.findings.every((f: any) => f.selectors.length === 2));
  assert.equal(drift.data.findings[0].expected[0].reference, 'var(--color-primary)');
  assert.equal(store.list<Finding>('findings', project.id).length, 2); assert.ok(drift.artifactIds.length >= 2);
  service.understanding.disposition(drift.data.findings[0].findingId, 'intentional');
  const suppressed = await service.understanding.drift(project.id, { routes: ['/design'] }); assert.equal(suppressed.data.findings.filter((f: any) => f.status === 'suppressed').length, 1);
  const element = await service.understanding.element(project.id, { route: '/design', selector: '#primary-button' });
  assert.equal(element.sources[0].file, 'src/components/Button.tsx'); assert.equal(element.sources[0].provenance, 'instrumented'); assert.ok(element.data.route.endsWith('/design'));
  const plain = await service.understanding.element(project.id, { route: '/design', selector: '#plain-button' }); assert.equal(plain.sources.length, 0); assert.match(plain.data.sourceConfidence, /Unknown/); assert.ok(plain.data.styles['background-color']);
  const risk = service.understanding.risk(project.id, { base: 'HEAD' });
  assert.ok(risk.data.changed.includes('src/components/Button.tsx')); assert.deepEqual(risk.data.routes.map((r: any) => r.path).sort(), ['/catalog', '/checkout']); assert.equal(risk.data.tests[0].provenance, 'static');
  console.log('PASS: two deduplicated drift findings, persisted intentional-value policy, instrumented/unknown source confidence, and shared-component route/test impact.');
  const flow = service.saveFlow(project.id, { name: 'Saved failing flow', steps: [{ action: 'goto', url: '/design' }, { action: 'assertText', text: 'Missing expected outcome' }] });
  const run = service.run(flow.id); assert.equal((await service.active.get(run.id))!.status, 'failed');
  const task = service.saveTask(project.id, { name: 'Resume button work', files: ['src/components/Button.tsx'], urls: [project.baseUrl + '/design'], flowId: flow.id, branch: 'fix/button', notes: 'Review the shared component.' });
  const session = service.understanding.session(project.id, { note: 'Preserve this exact note.', nextStep: 'Compare the primary button token at line 2.', taskId: task.id, proposedAction: '' });
  assert.equal(session.lastFailedRunId, run.id); assert.equal(session.git.branch, 'main'); assert.equal(session.git.dirty, true); assert.equal(session.proposedAction, '');
  assert.match(service.previewTask(task.id).branchMessage, /paused/);
  const bundle = handoff(store, { kind: 'finding', id: drift.data.findings[0].findingId }); assert.match(bundle.text, /Primary button|Card spacing/); assert.match(bundle.text, /artifacts/); assert.match(bundle.text, /Compare the primary button token/);
  await stopDemo(); demo = startDemo(4418, true); await once(demo, 'listening');
  const corrected = await service.understanding.drift(project.id, { routes: ['/design'] }); assert.equal(corrected.data.findings.length, 0); await stopDemo();
  store.close(); store = new Store(join(root, 'data')); service = new ControlRoom(store);
  const reopened = store.get<SessionSnapshot>('repo_snapshots', session.id); assert.equal(reopened.nextStep, session.nextStep); assert.equal(reopened.taskId, task.id); assert.equal(reopened.lastFailedRunId, run.id); assert.equal(store.get<Report>('reports', element.id).sources[0].file, 'src/components/Button.tsx');
  dashboard = startServer(4318, store); await once(dashboard.server, 'listening'); browser = await chromium.launch(); const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, permissions: ['clipboard-read', 'clipboard-write'] }); const page = await context.newPage(); const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto('http://127.0.0.1:4318'); await page.getByRole('combobox', { name: 'Current project' }).selectOption(project.id);
  await page.getByRole('button', { name: 'Context Resurrection', exact: true }).click(); await page.getByLabel('Exact next step').waitFor(); assert.equal(await page.getByLabel('Exact next step').inputValue(), session.nextStep); await page.getByRole('button', { name: 'Resume saved workspace' }).click(); await page.getByRole('dialog', { name: task.name }).waitFor(); assert.match(await page.getByRole('dialog', { name: task.name }).innerText(), /branch switching is paused/); await page.getByRole('button', { name: 'Close dialog', exact: true }).click();
  await page.getByRole('button', { name: 'Copy context for AI', exact: true }).last().click(); await page.getByRole('button', { name: 'Copy full context' }).waitFor(); await page.getByRole('button', { name: 'Copy full context' }).click(); const copied = await page.evaluate(() => navigator.clipboard.readText()); assert.match(copied, /Preserve this exact note/); assert.match(copied, /dcr-ai-context-v1/); await page.getByRole('button', { name: 'Close AI context' }).click();
  await page.getByRole('button', { name: 'PR Risk Map', exact: true }).click(); await page.getByRole('heading', { name: 'Affected routes' }).waitFor(); assert.match(await page.locator('main').innerText(), /\/catalog/); mkdirSync('test-results', { recursive: true }); await page.screenshot({ path: 'test-results/risk-map.png', fullPage: true });
  await page.getByRole('button', { name: 'Design Drift Detector', exact: true }).click(); await page.getByRole('combobox', { name: 'Saved reports' }).selectOption(drift.id); await page.getByText('Primary button · background-color', { exact: true }).waitFor(); await page.screenshot({ path: 'test-results/design-drift.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 }); assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), true); await page.screenshot({ path: 'test-results/design-drift-mobile.png', fullPage: true });
  assert.deepEqual(errors, []); await browser.close(); browser = undefined;
  await new Promise<void>(resolve => dashboard!.server.close(() => resolve())); dashboard = undefined;
  service.deleteProject(project.id, project.name); assert.equal(store.list('reports').length, 0); assert.equal(store.list('repo_snapshots').length, 0);
  console.log('PASS: corrected tokens pass; offline reopen restores exact note, branch, failed flow and task; dashboard resume preview, clipboard handoff, reports, mobile layout and deletion all work.');
  console.log('Phase 3 and 4 gates verified (editor-host command is checked separately).');
} finally { await browser?.close(); await stopDemo(); if (dashboard) await new Promise<void>(resolve => dashboard!.server.close(() => resolve())); store.close(); rmSync(root, { recursive: true, force: true }); }
